clippings/paper

.github/workflows/npm-publish.yml
.npmignore
package.json

Kz-205 Automate publish process

---

package.json
src/assets/scss/components.scss
src/components/Heading/Heading.tsx
src/components/Heading/types/HeadingPropsType.ts
src/components/List.tsx
src/components/List/List.tsx
src/components/List/enums/ListSpacingEnum.ts
src/components/List/types/ListPropsType.ts
src/components/ListItem/ListItem.tsx
src/components/ListItem/enums/ListItemSizeEnum.ts
src/components/ListItem/types/ListItemPropsType.ts
src/components/Text/Text.tsx
src/components/Text/types/TextPropsType.ts
src/core/config/ClassNames.ts
src/core/utils/ClassNameModifierUtil.ts
src/index.components.ts
src/index.enums.ts
src/stories/List/List.stories.tsx

KZ-267 Synchronise implementations

---

.eslintignore
package.json
src/index.d.ts
tsconfig.json
webpack.config.js

Update webpack config to generate library suitable code

Update webpack config 

---

package.json
yarn.lock

Add missing style-loader package.

---

package.json
src/assets/scss/components.scss
src/components/Heading/Heading.tsx
src/components/Heading/enums/HeadingEnum.ts
src/components/Text/Text.tsx
src/components/Text/enums/TextTypeEnum.ts
src/core/config/ClassNames.ts
src/stories/Headings/Headings.stories.tsx

Sync components with Clippings  internal implementation

Concurrency issues

---

.storybook/addons.js
.storybook/preview.js
package.json
src/assets/scss/forms.scss
src/assets/scss/select.scss
src/components/FormError/FormError.tsx
src/components/FormError/types/FormErrorPropType.ts
src/components/FormGroup/FormGroup.tsx
src/components/FormGroup/types/FormGroupPropType.ts
src/components/Label/Label.tsx
src/components/Label/types/LabelPropType.ts
src/components/ListNumber.tsx
src/components/ListNumber/ListNumber.tsx
src/components/ListNumber/types/ListNumberPropType.ts
src/components/Select/Select.tsx
src/components/Select/types/SelectPropsType.ts
src/components/TextInput/TextInput.tsx
src/components/TextInput/types/TextInputPropsType.ts
src/components/__tests__/__snapshots__/Select.tsx.snap
src/core/config/ClassNames.ts
src/index.components.ts
src/index.d.ts
src/stories/ListNumber/ListNumber.stories.tsx
src/stories/Select/Select.stories.tsx
src/stories/TextInput/TextInput.stories.tsx
yarn.lock

Migrating changes done in https://github.com/clippings/clippings/pull/7458
- Extract `FormGroup` from `TextInput`
- Extract `FormError` from `TextInput`
- Extract `Label` from `TextInput`
- Add forwardRef to `TextInput`
- Add forwardRef to `Select`
- Add max-height to `Select`
- Use `text-200` for form texts

Registration related fixes

---

src/index.d.ts

FormGroup type fix

---

babel.config.js
package.json
webpack.config.js
yarn.lock

Adding all the packages needed for the styled-components and styled-theming.

KZ-315 Add styled-components and styled-theming

---

package.json
src/assets/scss/_placeholders.scss
src/assets/scss/_variables.scss
src/assets/scss/components.scss
src/components/Heading/enums/HeadingEnum.ts
src/core/config/ClassNames.ts
src/stories/Headings/Headings.stories.tsx

Adding a medium heading for:
https://www.figma.com/file/G7mOyZ2fCIwlRHsDxpZPhr/Concept-%E2%80%94-Edit-variants-from-product-modals?node-id=621%3A1826

add new heading

---

package.json
src/assets/scss/components.scss
src/components/Overlay/Overlay.tsx
src/components/Overlay/enums/OverlayPositioningEnum.ts
src/components/Overlay/types/OverlayPropsType.ts
src/core/config/ClassNames.ts
src/index.components.ts
src/index.d.ts
src/stories/Overlay/Overlay.stories.tsx

DEM-1875 overlay component

---

package.json
src/index.d.ts

Correctly export the new header type

Export medium header

---

package.json
src/assets/scss/components.scss

At the moment we have a class, but no css for small spaces in lists.  This pr adds that spacing

Add spacing to small spacing list

---

.github/workflows/gh-pages.yml
.gitignore
README.md

- Add install and usage in readme
- Publish every change on master from Storybook to GitHub Pages website

GitHub Pages

---

src/index.d.ts

Added missing drawer type definitions.

Added missing drawer type definitions

---

package.json
src/assets/scss/_variables.scss
src/assets/scss/forms.scss
src/components/Drawer/Drawer.tsx
src/components/FormGroup/FormGroup.tsx
src/components/FormGroup/types/FormGroupPropType.ts
src/components/TextInput/TextInput.tsx
src/core/config/ClassNames.ts
src/stories/Drawer/BasicDrawerUsage.tsx
src/stories/TextInput/TextInput.stories.tsx

Added disabled state of the textInput

Disabled input

---

src/assets/scss/_variables.scss
src/components/Icon/enums/IconsColorEnum.ts
src/components/__tests__/__snapshots__/AutocompleteInput.tsx.snap
src/components/__tests__/__snapshots__/SearchInput.tsx.snap
src/core/styles/variables.ts

**What is this about?**
https://clippings.atlassian.net/browse/KZ-542
**Checklist**

KZ-542 change graphite-60

---

package.json
src/components/Buttons/styles/ButtonStyles.ts

Align the buttons padding as per design

Buttons design alignment

---

package.json
src/components/InputField/InputField.tsx

Remove the class passed to the input

Remove the passed class from the input

---

package.json
src/assets/scss/forms.scss
src/components/InputField/InputField.tsx
src/components/InputField/types/FieldPropsType.ts
src/core/config/ClassNames.ts
src/stories/SimpleInputTypes/SimpleInputTypes.stories.mdx

DD-71 
Adding note section to the `nputField`

DD-71 Add note section to input

---

package.json
src/assets/scss/forms.scss
src/components/FieldContainer/FieldContainer.tsx
src/components/FieldContainer/types/FieldContainerPropTypes.ts
src/components/InputField/InputField.tsx
src/components/TextareaField/TextareaField.tsx
src/components/TextareaField/types/TextareaPropsType.ts
src/core/config/ClassNames.ts
src/index.components.ts
src/stories/Textarea/Textarea.stories.mdx

DD-71 Create textarea field
